#!/bin/bash

# Check if prices are actually saved in database
# This will connect to Neon DB and verify current_price_per_unit values

echo "=== Checking Prices in Database ==="
echo ""
echo "⚠️  Need to run SQL query on Neon.tech dashboard:"
echo ""
echo "SELECT"
echo "  ufi.id,"
echo "  ufi.user_id,"
echo "  i.name as ingredient_name,"
echo "  ufi.quantity,"
echo "  ufi.unit,"
echo "  ufi.current_price_per_unit,"
echo "  ufi.current_price_currency,"
echo "  ufi.price_updated_at"
echo "FROM user_fridge_items ufi"
echo "JOIN \"Ingredient\" i ON ufi.ingredient_id = i.id"
echo "WHERE ufi.user_id = '924a278d-bdb6-4ad5-9167-d9e9495f6dab'"
echo "  AND ufi.current_price_per_unit IS NOT NULL"
echo "ORDER BY i.name;"
echo ""
echo "Expected results (if prices are saved):"
echo "  Wołowina: 0.02056 PLN/g (20.56 PLN/kg)"
echo "  Mleko:    0.00324 PLN/ml (3.24 PLN/l)"
echo "  Ogórek:   0.00700 PLN/g (7.00 PLN/kg)"
echo "  Cebula:   0.00345 PLN/g (3.45 PLN/kg)"
echo ""
echo "❌ If current_price_per_unit = NULL → prices NOT saved in DB"
echo "   → Backend CANNOT calculate economy"
echo "   → Need to check frontend price input + backend save logic"
