#!/bin/bash

# Check if ingredient exists in Ingredient catalog
# Usage: ./check_ingredient_in_catalog.sh "Olej roślinny"

INGREDIENT="${1:-Olej}"

echo "=== Checking Ingredient in Catalog ==="
echo ""
echo "🔍 Searching for: $INGREDIENT"
echo ""
echo "📋 Run this SQL query on Neon.tech dashboard:"
echo ""
echo "SELECT"
echo "  id,"
echo "  name,"
echo "  category,"
echo "  default_unit,"
echo "  created_at"
echo "FROM \"Ingredient\""
echo "WHERE LOWER(name) LIKE LOWER('%${INGREDIENT}%')"
echo "ORDER BY name;"
echo ""
echo "---"
echo ""
echo "Alternative: Check all oils:"
echo ""
echo "SELECT id, name, category, default_unit"
echo "FROM \"Ingredient\""
echo "WHERE LOWER(name) LIKE '%olej%'"
echo "OR LOWER(name) LIKE '%oil%'"
echo "ORDER BY name;"
echo ""
echo "---"
echo ""
echo "To add if missing:"
echo ""
echo "INSERT INTO \"Ingredient\" (id, name, category, default_unit)"
echo "VALUES ("
echo "  gen_random_uuid(),"
echo "  'Olej roślinny',"
echo "  'pantry',"
echo "  'ml'"
echo ");"
