package models

import (
	"time"

	"github.com/google/uuid"
)

// DishStatus represents the lifecycle state of a dish
type DishStatus string

const (
	DishStatusDraft     DishStatus = "draft"      // AI generated, needs review
	DishStatusApproved  DishStatus = "approved"   // Admin reviewed & approved
	DishStatusPublished DishStatus = "published"  // Available for customers
)

// Dish represents a commercial dish card for marketplace
// 
// Architecture principle: Copy Recipe pipeline → adapt for Dish
// - Uses same AI generation pattern as Recipe
// - Has draft → approved → published lifecycle
// - Admin always controls before publishing
// - Cost is a snapshot (not dependent on fridge directly)
type Dish struct {
	ID       uuid.UUID `gorm:"type:uuid;primary_key;default:uuid_generate_v4()" json:"id"`
	RecipeID uuid.UUID `gorm:"type:uuid;not null;index" json:"recipeId"` // FK to Recipe.id

	// Content (generated by AI or manually edited)
	Title       string `gorm:"type:varchar(255);not null" json:"title"`
	Description string `gorm:"type:text" json:"description"`
	ImageURL    string `gorm:"column:image_url;type:text" json:"imageUrl"`

	// Finance (core business logic)
	// Cost = snapshot of ingredient costs at creation time
	// Price = selling price (calculated from cost + margin)
	// Margin = profit margin percentage (0-100)
	Cost   float64 `gorm:"type:decimal(10,2);not null;check:cost >= 0" json:"cost"`       // Cost to make (PLN)
	Price  float64 `gorm:"type:decimal(10,2);not null;check:price >= 0" json:"price"`     // Selling price (PLN)
	Margin float64 `gorm:"type:decimal(5,2);not null;check:margin >= 0 AND margin <= 100" json:"margin"` // Margin %

	// Status lifecycle (mirrors Recipe pattern)
	Status      DishStatus `gorm:"type:varchar(20);not null;default:'draft';check:status IN ('draft', 'approved', 'published')" json:"status"`
	IsAvailable bool       `gorm:"not null;default:true;index" json:"isAvailable"` // Updated by background job

	// Metadata
	// NOTE: User.id is TEXT type (not UUID) in database
	CreatedBy  string  `gorm:"type:text;not null;index" json:"createdBy"`   // Admin who created (TEXT FK to User.id)
	ApprovedBy *string `gorm:"type:text" json:"approvedBy,omitempty"`       // Admin who approved (TEXT FK to User.id)
	ApprovedAt *time.Time `json:"approvedAt,omitempty"`

	CreatedAt time.Time `gorm:"not null;default:NOW()" json:"createdAt"`
	UpdatedAt time.Time `gorm:"not null;default:NOW()" json:"updatedAt"`

	// Relations (preload with GORM)
	Recipe   RecipeCatalog `gorm:"foreignKey:RecipeID" json:"recipe,omitempty"`
	Creator  User          `gorm:"foreignKey:CreatedBy" json:"creator,omitempty"`
	Approver *User         `gorm:"foreignKey:ApprovedBy" json:"approver,omitempty"`
}

// TableName specifies the table name for GORM
func (Dish) TableName() string {
	return "dishes"
}

// IsEditable checks if dish can be edited (only draft and approved can be edited)
func (d *Dish) IsEditable() bool {
	return d.Status == DishStatusDraft || d.Status == DishStatusApproved
}

// CanApprove checks if dish can be approved (only draft can be approved)
func (d *Dish) CanApprove() bool {
	return d.Status == DishStatusDraft
}

// CanPublish checks if dish can be published (only approved can be published)
func (d *Dish) CanPublish() bool {
	return d.Status == DishStatusApproved
}

// CalculateProfit returns the profit amount (price - cost)
func (d *Dish) CalculateProfit() float64 {
	return d.Price - d.Cost
}

// CalculateActualMargin returns the actual margin percentage
func (d *Dish) CalculateActualMargin() float64 {
	if d.Price == 0 {
		return 0
	}
	return ((d.Price - d.Cost) / d.Price) * 100
}
