-- Migration 063: Add auto_translated column to Ingredient table
-- Date: 2026-01-06
-- Purpose: Track whether ingredient translations were created by AI or manually

-- Add auto_translated column
ALTER TABLE "Ingredient" 
ADD COLUMN IF NOT EXISTS auto_translated BOOLEAN DEFAULT false;

-- Set existing ingredients as manually translated (not auto)
UPDATE "Ingredient" 
SET auto_translated = false 
WHERE auto_translated IS NULL;

-- Add comment
COMMENT ON COLUMN "Ingredient".auto_translated IS 'True if translations were generated by AI, false if manual';

-- Verify
SELECT COUNT(*) as total_ingredients,
       COUNT(CASE WHEN auto_translated = true THEN 1 END) as auto_translated,
       COUNT(CASE WHEN auto_translated = false THEN 1 END) as manual
FROM "Ingredient";
